// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// newtissue
RcppExport SEXP newtissue(SEXP cat_, SEXP block_id_, SEXP nclust_, SEXP bins_, SEXP fs_binned_, SEXP alpha_, SEXP inner_iters_);
RcppExport SEXP FUNLDA_newtissue(SEXP cat_SEXP, SEXP block_id_SEXP, SEXP nclust_SEXP, SEXP bins_SEXP, SEXP fs_binned_SEXP, SEXP alpha_SEXP, SEXP inner_iters_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type cat_(cat_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type block_id_(block_id_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type nclust_(nclust_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bins_(bins_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fs_binned_(fs_binned_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inner_iters_(inner_iters_SEXP);
    __result = Rcpp::wrap(newtissue(cat_, block_id_, nclust_, bins_, fs_binned_, alpha_, inner_iters_));
    return __result;
END_RCPP
}
// ebmme_cpp_binned
RcppExport SEXP ebmme_cpp_binned(SEXP dat_, SEXP cat_, SEXP block_id_, SEXP H1_inv_, SEXP p_, SEXP alpha_, SEXP iters_, SEXP inner_iters_, SEXP nclust_, SEXP bins_, SEXP bin_data_, SEXP kde_nbins_);
RcppExport SEXP FUNLDA_ebmme_cpp_binned(SEXP dat_SEXP, SEXP cat_SEXP, SEXP block_id_SEXP, SEXP H1_inv_SEXP, SEXP p_SEXP, SEXP alpha_SEXP, SEXP iters_SEXP, SEXP inner_iters_SEXP, SEXP nclust_SEXP, SEXP bins_SEXP, SEXP bin_data_SEXP, SEXP kde_nbins_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type dat_(dat_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type cat_(cat_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type block_id_(block_id_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type H1_inv_(H1_inv_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iters_(iters_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inner_iters_(inner_iters_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type nclust_(nclust_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bins_(bins_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bin_data_(bin_data_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type kde_nbins_(kde_nbins_SEXP);
    __result = Rcpp::wrap(ebmme_cpp_binned(dat_, cat_, block_id_, H1_inv_, p_, alpha_, iters_, inner_iters_, nclust_, bins_, bin_data_, kde_nbins_));
    return __result;
END_RCPP
}
// predictlogsum
RcppExport SEXP predictlogsum(SEXP cat_, SEXP block_id_, SEXP nclust_, SEXP bins_, SEXP fs_binned_, SEXP a_);
RcppExport SEXP FUNLDA_predictlogsum(SEXP cat_SEXP, SEXP block_id_SEXP, SEXP nclust_SEXP, SEXP bins_SEXP, SEXP fs_binned_SEXP, SEXP a_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type cat_(cat_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type block_id_(block_id_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type nclust_(nclust_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bins_(bins_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fs_binned_(fs_binned_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_(a_SEXP);
    __result = Rcpp::wrap(predictlogsum(cat_, block_id_, nclust_, bins_, fs_binned_, a_));
    return __result;
END_RCPP
}
